"""Initialize DB

Revision ID: 1b9b5d283c97
Revises: 
Create Date: 2025-03-31 19:35:07.119573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9b5d283c97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('port', sa.BigInteger(), nullable=False),
    sa.Column('schema', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_systems_id'), 'systems', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_systems_id'), table_name='systems', schema='public')
    op.drop_table('systems', schema='public')
    # ### end Alembic commands ###
